# Generated by Django 5.2.3 on 2025-07-30 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombre_juego', models.CharField(blank=True, help_text='Nombre visible en el juego (nickname). Déjalo vacío para usar el nombre de usuario.', max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('directa', 'Respuesta Directa'), ('multiple_choice', 'Opción Múltiple')], max_length=20)),
                ('enunciado', models.TextField()),
                ('respuesta_correcta', models.CharField(blank=True, max_length=100, null=True)),
                ('dificultad', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('orden', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('orden', models.PositiveIntegerField()),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pistas', to='escape_Juego.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('es_correcta', models.BooleanField(default=False)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='escape_Juego.pregunta')),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='escape_Juego.sala'),
        ),
        migrations.CreateModel(
            name='Intento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('tiempo_total', models.DurationField(blank=True, null=True)),
                ('pistas_totales_usadas', models.PositiveIntegerField(default=0)),
                ('puntaje', models.IntegerField(default=100)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escape_Juego.jugador')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escape_Juego.sala')),
            ],
        ),
    ]
