# Generated by Django 5.2.3 on 2025-08-01 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escape_Juego', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jugador',
            options={'verbose_name': 'Nombre de Perfil', 'verbose_name_plural': 'Jugadores'},
        ),
    ]
