# Generated by Django 5.2.3 on 2025-07-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escape_Juego', '0002_remove_pregunta_respuesta_correcta_opcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='fecha_jugada',
        ),
        migrations.AddField(
            model_name='jugador',
            name='tiempo_final',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jugador',
            name='tiempo_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jugador',
            name='tiempo_total',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
