# Generated by Django 5.2.3 on 2025-08-09 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escape_Juego', '0002_alter_jugador_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pista',
            name='pregunta',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='es_pregunta_principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='nombre_juego',
            field=models.CharField(blank=True, help_text='Nombre visible en el juego (nickname). Déjalo vacío para usar el nombre de usuario.', max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completada', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('tiempo_total', models.DurationField(blank=True, null=True)),
                ('pistas_totales_usadas', models.PositiveIntegerField(default=0)),
                ('puntaje', models.IntegerField(default=100)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escape_Juego.jugador')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escape_Juego.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_dada', models.CharField(max_length=200)),
                ('es_correcta', models.BooleanField()),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='escape_Juego.partida')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escape_Juego.pregunta')),
            ],
        ),
        migrations.DeleteModel(
            name='Intento',
        ),
        migrations.DeleteModel(
            name='Pista',
        ),
    ]
