# Generated by Django 5.2.3 on 2025-08-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escape_Juego', '0003_remove_pista_pregunta_pregunta_es_pregunta_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='target',
            field=models.CharField(default='default-target', max_length=50),
        ),
    ]
