# Generated by Django 5.2.3 on 2025-08-11 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escape_Juego', '0004_pregunta_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcion',
            name='pregunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='escape_Juego.pregunta'),
        ),
    ]
