# Generated by Django 5.2.3 on 2025-08-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escape_Juego', '0006_sala_fecha_desbloqueo_progresousuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pregunta',
            options={'ordering': ['target', 'order']},
        ),
        migrations.AddField(
            model_name='pregunta',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text="El orden en que aparecerá la pregunta. Las preguntas con el mismo 'target' se ordenarán según este número."),
        ),
        migrations.AlterUniqueTogether(
            name='pregunta',
            unique_together={('target', 'order')},
        ),
    ]
