# Generated by Django 5.2.3 on 2025-08-13 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escape_Juego', '0007_alter_pregunta_options_pregunta_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('enunciado_mision', models.TextField()),
                ('instrucciones', models.TextField()),
                ('tabla', models.JSONField()),
                ('candado_intermedio_pregunta', models.CharField(max_length=255)),
                ('candado_intermedio_respuesta', models.CharField(max_length=100)),
                ('target', models.CharField(default='default-target', max_length=50)),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='misiones', to='escape_Juego.sala')),
            ],
        ),
    ]
