# Generated by Django 5.2.3 on 2025-08-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escape_Juego', '0008_mision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mision',
            options={'ordering': ['target', 'order']},
        ),
        migrations.AddField(
            model_name='mision',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='El orden en que aparecerá esta misión dentro de su target.'),
        ),
        migrations.AlterUniqueTogether(
            name='mision',
            unique_together={('target', 'order')},
        ),
    ]
