# Generated by Django 5.2.3 on 2025-08-13 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escape_Juego', '0009_alter_mision_options_mision_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mision',
            name='tabla',
        ),
        migrations.CreateModel(
            name='FilaTabla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fila', models.CharField(help_text='Ejemplo: z1, z2, etc.', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('mision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas_tabla', to='escape_Juego.mision')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CeldaTabla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encabezado_columna', models.CharField(help_text='Ejemplo: parte_real, parte_imaginaria', max_length=50)),
                ('respuesta_correcta', models.CharField(max_length=200)),
                ('fila_tabla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celdas', to='escape_Juego.filatabla')),
            ],
        ),
    ]
