# Generated by Django 5.2.3 on 2025-08-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escape_Juego', '0010_remove_mision_tabla_filatabla_celdatabla'),
    ]

    operations = [
        migrations.AddField(
            model_name='mision',
            name='pregunta_final',
            field=models.TextField(blank=True, help_text='Pregunta que se mostrará en la misión final.', null=True),
        ),
        migrations.AddField(
            model_name='mision',
            name='respuesta_final',
            field=models.CharField(blank=True, help_text='Respuesta correcta para la misión final.', max_length=255, null=True),
        ),
    ]
