# Generated by Django 5.2.3 on 2025-08-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escape_Juego', '0011_mision_pregunta_final_mision_respuesta_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mision',
            name='candado_intermedio_pregunta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mision',
            name='candado_intermedio_respuesta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mision',
            name='enunciado_mision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mision',
            name='instrucciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mision',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
