# Generated by Django 5.2.3 on 2025-08-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escape_Juego', '0012_alter_mision_candado_intermedio_pregunta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='celdatabla',
            name='es_campo_rellenable',
            field=models.BooleanField(default=True, help_text='Marcar si el usuario debe rellenar este campo en la tabla.'),
        ),
    ]
