# Generated by Django 5.2.3 on 2025-08-18 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escape_Juego', '0013_celdatabla_es_campo_rellenable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='pregunta',
        ),
        migrations.AddField(
            model_name='respuesta',
            name='celda',
            field=models.ForeignKey(blank=True, help_text='Celda de tabla (si aplica).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='escape_Juego.celdatabla'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='mision',
            field=models.ForeignKey(blank=True, help_text='Misión asociada (candado o final).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='escape_Juego.mision'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='respuesta_dada',
            field=models.TextField(),
        ),
    ]
