# Generated by Django 5.2.3 on 2025-08-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escape_Juego', '0014_remove_respuesta_pregunta_respuesta_celda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='tipo_respuesta',
            field=models.CharField(default='final', max_length=20),
        ),
    ]
