# Generated by Django 5.2.3 on 2025-08-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escape_Juego', '0015_respuesta_tipo_respuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='pistas_totales_usadas',
        ),
        migrations.AddField(
            model_name='partida',
            name='misiones_completadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partida',
            name='total_misiones',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partida',
            name='puntaje',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
