# Generated by Django 5.2.3 on 2025-08-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escape_Juego', '0016_remove_partida_pistas_totales_usadas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='misiones_completadas',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='total_misiones',
        ),
        migrations.AlterField(
            model_name='partida',
            name='puntaje',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
    ]
