# Generated by Django 5.2.3 on 2025-09-01 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escape_Juego', '0017_remove_partida_misiones_completadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='nombre_configurado_manualmente',
            field=models.BooleanField(default=False, help_text='Indica si el usuario ya configuró su nombre de juego manualmente'),
        ),
    ]
